"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Archive, ArrowLeft, Check, History, LogOut, PackageOpen, Plus, Search, Settings, ShoppingBasket, Trash2 } from "lucide-react";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type ListName = "grocery" | "pantry";
type TabName = ListName | "settings";
type Item = { id: string; description: string; quantity?: string; list: ListName; completed?: boolean; createdAt: number; updatedAt: number };
type Actor = { uid: string; email: string; displayName?: string | null; photoURL?: string | null };
type LogEntry = { id: string; action: string; description: string; quantity?: string; fromList?: ListName; toList?: ListName; actorEmail: string; actorName?: string; createdAt: number };
type FirebaseBridge = { signIn(): Promise<void>; signOut(): Promise<void>; addItem(input: { description: string; quantity: string; list: ListName }): Promise<void>; updateItem(id: string, input: { description: string; quantity: string }): Promise<void>; deleteItem(item: Item): Promise<void>; toggleBought(item: Item): Promise<void>; moveItem(item: Item, toList: ListName): Promise<void>; clearCompleted(items: Item[]): Promise<void> };
type ModelContext = { registerTool(tool: { name: string; title: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute(input: unknown): unknown | Promise<unknown> }, options: { signal: AbortSignal }): void | Promise<void> };

declare global { interface Window { JamjarFirebase?: FirebaseBridge; JamjarCurrentUser?: Actor | null; JamjarData?: { items: Item[]; history: LogEntry[]; fromCache: boolean }; JamjarInstallPrompt?: Event & { prompt(): Promise<void> } } }

const WARM = ["#c3444d", "#c94a45", "#ce523e", "#d15b38", "#d16435", "#cf6e34", "#ca7937", "#c3823c", "#b98b44", "#ad934e", "#9f9959"];
const COOL = ["#3c8498", "#428097", "#497c95", "#507794", "#587292", "#606d8e", "#69688a", "#726387", "#7c5f82", "#875b7b", "#925873"];
const SAMPLE_ITEMS: Item[] = [
  { id: "sample-1", description: "Stone-ground spaghetti", quantity: "2 packs", list: "grocery", createdAt: 3, updatedAt: 3 },
  { id: "sample-2", description: "Fresh basil", quantity: "2 bunches", list: "grocery", createdAt: 2, updatedAt: 2 },
  { id: "sample-3", description: "Parmigiano Reggiano", list: "grocery", completed: true, createdAt: 1, updatedAt: 1 },
  { id: "sample-4", description: "San Marzano tomatoes", quantity: "4 cans", list: "pantry", createdAt: 4, updatedAt: 4 },
  { id: "sample-5", description: "Fish sauce", quantity: "1 bottle", list: "pantry", createdAt: 3, updatedAt: 3 },
  { id: "sample-6", description: "Dried chickpeas", quantity: "1 bag", list: "pantry", createdAt: 2, updatedAt: 2 },
];

function rowColor(index: number, count: number, palette: string[]) { if (count <= 1) return palette[5]; const pct = count <= 11 ? (100 - (count - 1) * 10) / 2 + index * 10 : index * 100 / (count - 1); return palette[Math.max(0, Math.min(10, Math.round(pct / 10)))]; }
function titleCase(value: string) { return value ? value[0].toUpperCase() + value.slice(1) : value; }

function SwipeRow({ item, index, count, onEdit, onToggle, onMove }: { item: Item; index: number; count: number; onEdit(): void; onToggle(): void; onMove(): void }) {
  const rowRef = useRef<HTMLButtonElement>(null); const startX = useRef(0); const lastX = useRef(0); const dragged = useRef(false); const [offset, setOffset] = useState(0);
  const direction = item.list === "grocery" ? 1 : -1;
  const transfer = Math.abs(offset) >= (typeof window === "undefined" ? 720 : window.innerWidth) * 2 / 3;
  const primaryLabel = item.list === "grocery" ? (item.completed ? "Restore" : "Bought") : "Move to Grocery";
  const transferLabel = item.list === "grocery" ? "Move to Pantry" : "Move to Grocery";
  const finish = () => { const distance = Math.abs(lastX.current); const longAt = window.innerWidth * 2 / 3; setOffset(0); if (distance >= longAt) onMove(); else if (distance >= 64) item.list === "grocery" ? onToggle() : onMove(); };
  return <li className={`swipe-wrap ${item.completed ? "is-done" : ""}`} style={{ "--row-color": item.completed ? "transparent" : rowColor(index, count, item.list === "grocery" ? WARM : COOL) } as React.CSSProperties}>
    <div className={`swipe-underlay ${transfer ? "is-transfer" : ""} ${item.list === "pantry" ? "from-right" : ""}`}>{transfer ? <Archive aria-hidden="true" /> : item.list === "grocery" ? <Check aria-hidden="true" /> : <ShoppingBasket aria-hidden="true" />}<span>{transfer ? transferLabel : primaryLabel}</span></div>
    <button ref={rowRef} className="item-row" style={{ transform: `translateX(${offset}px)` }} onPointerDown={event => { startX.current = event.clientX; lastX.current = 0; dragged.current = false; rowRef.current?.setPointerCapture(event.pointerId); }} onPointerMove={event => { if (!rowRef.current?.hasPointerCapture(event.pointerId)) return; const raw = event.clientX - startX.current; const next = raw * direction > 0 ? raw : raw * 0.08; lastX.current = next; if (Math.abs(next) > 5) dragged.current = true; setOffset(next); }} onPointerUp={event => { if (rowRef.current?.hasPointerCapture(event.pointerId)) rowRef.current.releasePointerCapture(event.pointerId); finish(); }} onPointerCancel={() => { setOffset(0); lastX.current = 0; }} onClick={() => { if (!dragged.current) onEdit(); }} aria-label={`Edit ${item.description}`}>
      <span className="item-copy"><span>{item.description}</span>{item.quantity && <small>{item.quantity}</small>}</span>
    </button>
  </li>;
}

export default function JamjarApp() {
  const [isPreview, setIsPreview] = useState(false);
  const [tab, setTab] = useState<TabName>("grocery"); const [items, setItems] = useState<Item[]>([]); const [logs, setLogs] = useState<LogEntry[]>([]); const [actor, setActor] = useState<Actor | null>(null); const [authKnown, setAuthKnown] = useState(false); const [ready, setReady] = useState(false); const [historyOpen, setHistoryOpen] = useState(false); const [query, setQuery] = useState(""); const [editorOpen, setEditorOpen] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [description, setDescription] = useState(""); const [quantity, setQuantity] = useState(""); const [formError, setFormError] = useState(""); const [clearOpen, setClearOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false); const [status, setStatus] = useState("Connecting…"); const [installable, setInstallable] = useState(false);

  useEffect(() => {
    if (["terminal.local", "localhost", "127.0.0.1"].includes(window.location.hostname)) {
      setIsPreview(true); setItems(SAMPLE_ITEMS); setActor({ uid: "preview", email: "preview@jamjar.local", displayName: "Kevin" }); setAuthKnown(true); setReady(true); setStatus("Preview data");
    }
  }, []);

  useEffect(() => {
    const onReady = () => setReady(true); const onAuth = (event: Event) => { setActor((event as CustomEvent).detail); setAuthKnown(true); }; const onData = (event: Event) => { const detail = (event as CustomEvent).detail; setItems(detail.items); setLogs(detail.history); setStatus(detail.fromCache ? "Offline · changes will sync" : "Up to date"); }; const onError = (event: Event) => setStatus((event as CustomEvent).detail || "Sync unavailable");
    window.addEventListener("jamjar:firebase-ready", onReady); window.addEventListener("jamjar:auth", onAuth); window.addEventListener("jamjar:data", onData); window.addEventListener("jamjar:error", onError);
    const install = (event: Event) => { event.preventDefault(); window.JamjarInstallPrompt = event as typeof window.JamjarInstallPrompt; setInstallable(true); }; window.addEventListener("beforeinstallprompt", install); if (window.JamjarFirebase) { setReady(true); if (window.JamjarCurrentUser !== undefined) { setActor(window.JamjarCurrentUser); setAuthKnown(true); } if (window.JamjarData) { setItems(window.JamjarData.items); setLogs(window.JamjarData.history); } } if ("serviceWorker" in navigator && !["terminal.local", "localhost", "127.0.0.1"].includes(window.location.hostname)) navigator.serviceWorker.register("/jamjar/sw.js", { scope: "/jamjar/" });
    return () => { window.removeEventListener("jamjar:firebase-ready", onReady); window.removeEventListener("jamjar:auth", onAuth); window.removeEventListener("jamjar:data", onData); window.removeEventListener("jamjar:error", onError); window.removeEventListener("beforeinstallprompt", install); };
  }, [isPreview]);
  useEffect(() => { const pop = () => { setHistoryOpen(false); setEditorOpen(false); }; window.addEventListener("popstate", pop); return () => window.removeEventListener("popstate", pop); }, []);

  const active = useMemo(() => items.filter(i => i.list === "grocery" && !i.completed).sort((a, b) => b.createdAt - a.createdAt), [items]); const completed = useMemo(() => items.filter(i => i.list === "grocery" && i.completed).sort((a, b) => b.updatedAt - a.updatedAt), [items]); const pantry = useMemo(() => items.filter(i => i.list === "pantry" && i.description.toLowerCase().includes(query.trim().toLowerCase())).sort((a, b) => a.description.localeCompare(b.description)), [items, query]); const suggestions = useMemo(() => Array.from(new Set([...items.map(i => i.description), ...logs.map(l => l.description)])).sort(), [items, logs]);
  const localAction = useCallback((action: string, item: Item, patch?: Partial<Item>) => { if (!isPreview) return; const now = Date.now(); if (action === "add") setItems(v => [{ ...item, ...patch }, ...v]); else if (action === "delete") setItems(v => v.filter(x => x.id !== item.id)); else setItems(v => v.map(x => x.id === item.id ? { ...x, ...patch, updatedAt: now } : x)); setLogs(v => [{ id: crypto.randomUUID(), action, description: item.description, quantity: item.quantity, actorEmail: actor?.email || "", actorName: actor?.displayName || "Kevin", createdAt: now, fromList: item.list, toList: patch?.list }, ...v]); }, [actor, isPreview]);
  const openEditor = (item: Item | null = null) => { setEditing(item); setDescription(item?.description || ""); setQuantity(item?.quantity || ""); setFormError(""); setEditorOpen(true); history.pushState({ editor: true }, ""); };
  const closeEditor = () => { setEditorOpen(false); setEditing(null); if (history.state?.editor) history.back(); };
  const saveItem = async () => { const clean = description.trim(); const qty = quantity.trim(); const destination = editing?.list || (tab === "pantry" ? "pantry" : "grocery"); if (!clean) { setFormError("Add a description."); return; } const duplicate = items.find(i => i.list === destination && i.id !== editing?.id && i.description.trim().toLowerCase() === clean.toLowerCase()); if (duplicate) { setFormError(`${clean} is already in ${destination === "grocery" ? "Grocery" : "Pantry"}.`); return; } try { if (editing) { if (isPreview) localAction("updated", editing, { description: clean, quantity: qty }); else await window.JamjarFirebase?.updateItem(editing.id, { description: clean, quantity: qty }); } else { const item: Item = { id: crypto.randomUUID(), description: clean, quantity: qty, list: destination, createdAt: Date.now(), updatedAt: Date.now() }; if (isPreview) localAction("add", item); else await window.JamjarFirebase?.addItem({ description: clean, quantity: qty, list: destination }); } closeEditor(); } catch { setFormError("Jamjar couldn’t save that change. Try again."); } };
  const toggle = async (item: Item) => { if (isPreview) localAction(item.completed ? "restored" : "bought", item, { completed: !item.completed }); else await window.JamjarFirebase?.toggleBought(item); };
  const move = async (item: Item, toList: ListName) => { const duplicate = items.find(i => i.list === toList && i.description.trim().toLowerCase() === item.description.trim().toLowerCase()); if (duplicate) { setStatus(`Already in ${toList === "pantry" ? "Pantry" : "Grocery"}`); return; } if (isPreview) localAction(toList === "pantry" ? "moved_to_pantry" : "moved_to_grocery", item, { list: toList, completed: false }); else await window.JamjarFirebase?.moveItem(item, toList); };
  const remove = async () => { if (!editing) return; if (isPreview) localAction("deleted", editing); else await window.JamjarFirebase?.deleteItem(editing); setDeleteOpen(false); closeEditor(); };
  const clearCompleted = async () => { if (isPreview) { const ids = new Set(completed.map(i => i.id)); setItems(v => v.filter(i => !ids.has(i.id))); completed.forEach(i => localAction("cleared", i)); } else await window.JamjarFirebase?.clearCompleted(completed); setClearOpen(false); };
  const showHistory = () => { setHistoryOpen(true); history.pushState({ history: true }, ""); };

  useEffect(() => {
    const context = (document as Document & { modelContext?: ModelContext }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    const add = context.registerTool({ name: "add_jamjar_item", title: "Add Jamjar item", description: "Add an item to the shared Grocery or Pantry list.", inputSchema: { type: "object", properties: { description: { type: "string", minLength: 1, maxLength: 120 }, quantity: { type: "string", maxLength: 40 }, list: { type: "string", enum: ["grocery", "pantry"] } }, required: ["description", "list"], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async input => { const value = input as { description?: string; quantity?: string; list?: ListName }; const clean = value.description?.trim(); if (!clean || !value.list || !["grocery", "pantry"].includes(value.list)) throw Error("A valid description and list are required."); if (items.some(i => i.list === value.list && i.description.toLowerCase() === clean.toLowerCase())) throw Error("That item is already on the list."); const item: Item = { id: crypto.randomUUID(), description: clean, quantity: value.quantity?.trim() || "", list: value.list, completed: false, createdAt: Date.now(), updatedAt: Date.now() }; if (isPreview) localAction("add", item); else await window.JamjarFirebase?.addItem({ description: clean, quantity: item.quantity || "", list: value.list }); return { added: clean, list: value.list }; } }, { signal: lifecycle.signal });
    const find = context.registerTool({ name: "find_pantry_items", title: "Find Pantry items", description: "Find currently stocked Pantry items by description.", inputSchema: { type: "object", properties: { query: { type: "string", maxLength: 120 } }, required: ["query"], additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: false }, execute: input => { const queryValue = String((input as { query?: string }).query || "").trim().toLowerCase(); return { items: items.filter(i => i.list === "pantry" && i.description.toLowerCase().includes(queryValue)).map(i => ({ description: i.description, quantity: i.quantity || "" })) }; } }, { signal: lifecycle.signal });
    Promise.all([Promise.resolve(add), Promise.resolve(find)]).catch(() => undefined);
    return () => lifecycle.abort();
  }, [actor, isPreview, items, localAction]);

  if (!authKnown && !isPreview) return <main className="gate"><div className="gate-card"><div className="jar-mark" aria-hidden="true"><span /></div><h1>Jamjar</h1><div className="gate-bands"><i /><i /><i /><i /></div><p>{ready ? "Sign in with Google to share your grocery list and pantry." : "Opening your lists…"}</p><Button className="google-button" disabled={!ready} onClick={() => window.JamjarFirebase?.signIn()}>Sign in with Google</Button></div></main>;
  if (!actor && !isPreview) return <main className="gate"><div className="gate-card"><div className="jar-mark" aria-hidden="true"><span /></div><h1>Jamjar</h1><div className="gate-bands"><i /><i /><i /><i /></div><p>One shared grocery list. One shared pantry.</p><Button className="google-button" disabled={!ready} onClick={() => window.JamjarFirebase?.signIn()}>Sign in with Google</Button><small>{status}</small></div></main>;
  if (historyOpen) return <main className="history-screen"><header className="screen-head"><button onClick={() => history.back()} aria-label="Back to Settings"><ArrowLeft /></button><h1>History Log</h1></header><ol className="history-list">{logs.length ? [...logs].sort((a,b)=>b.createdAt-a.createdAt).map(log => <li key={log.id}><span className="history-icon">{log.action.includes("pantry") ? <PackageOpen /> : log.action.includes("grocery") || log.action === "bought" ? <ShoppingBasket /> : log.action === "deleted" || log.action === "cleared" ? <Trash2 /> : <Check />}</span><div><strong>{log.actorName || log.actorEmail.split("@")[0]} {log.action.replaceAll("_", " ")} “{log.description}”</strong><small>{new Date(log.createdAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}{log.quantity ? ` · ${log.quantity}` : ""}</small></div></li>) : <li className="empty-state">Actions will appear here as you use Jamjar.</li>}</ol></main>;

  return <Tabs value={tab} onValueChange={v => setTab(v as TabName)} className="app-shell">
    <header className="topbar"><div className="brand"><div className="jar-mark small" aria-hidden="true"><span /></div><span>Jamjar</span></div><span className="sync-status">{status}</span></header>
    <main className="list-main">
      <section hidden={tab !== "grocery"} aria-labelledby="grocery-title"><div className="page-head"><div><span>Shared list</span><h1 id="grocery-title">Grocery</h1></div>{completed.length > 0 && <button className="clear-button" onClick={() => setClearOpen(true)}>Clear completed</button>}</div><ul className="item-list">{active.map((item, index) => <SwipeRow key={item.id} item={item} index={index} count={active.length} onEdit={() => openEditor(item)} onToggle={() => toggle(item)} onMove={() => move(item, "pantry")} />)}{active.length === 0 && <li className="empty-state">Your grocery list is empty.</li>}{completed.map((item, index) => <SwipeRow key={item.id} item={item} index={index} count={completed.length} onEdit={() => openEditor(item)} onToggle={() => toggle(item)} onMove={() => move(item, "pantry")} />)}</ul></section>
      <section hidden={tab !== "pantry"} aria-labelledby="pantry-title"><div className="page-head"><div><span>In stock</span><h1 id="pantry-title">Pantry</h1></div></div><label className="search-field"><Search aria-hidden="true"/><span className="sr-only">Search Pantry</span><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Filter pantry" /></label><ul className="item-list">{pantry.map((item, index) => <SwipeRow key={item.id} item={item} index={index} count={pantry.length} onEdit={() => openEditor(item)} onToggle={() => {}} onMove={() => move(item, "grocery")} />)}{pantry.length === 0 && <li className="empty-state">{query ? "No pantry items match." : "Your pantry is empty."}</li>}</ul></section>
      <section hidden={tab !== "settings"} className="settings-page" aria-labelledby="settings-title"><div className="page-head"><div><span>Jamjar</span><h1 id="settings-title">Settings</h1></div></div><button className="settings-row" onClick={showHistory}><span className="setting-icon"><History /></span><span><strong>History Log</strong><small>See every change and who made it</small></span><span aria-hidden="true">›</span></button><div className="settings-row static"><span className="avatar">{actor?.displayName?.[0] || actor?.email[0].toUpperCase()}</span><span><strong>{actor?.displayName || actor?.email}</strong><small>{actor?.email}</small></span></div>{installable && <button className="settings-row" onClick={() => window.JamjarInstallPrompt?.prompt()}><span className="setting-icon"><PackageOpen /></span><span><strong>Install Jamjar</strong><small>Add it to this device</small></span><span aria-hidden="true">›</span></button>}<button className="settings-row danger-row" onClick={() => window.JamjarFirebase?.signOut()}><span className="setting-icon"><LogOut /></span><span><strong>Sign out</strong><small>Keep shared data in Jamjar</small></span></button></section>
    </main>
    {tab !== "settings" && <button className="fab" onClick={() => openEditor()} aria-label={`Add to ${titleCase(tab)}`}><Plus /></button>}
    <TabsList className="bottom-tabs" aria-label="Jamjar sections"><TabsTrigger value="grocery"><ShoppingBasket/><span>Grocery</span>{active.length > 0 && <b>{active.length}</b>}</TabsTrigger><TabsTrigger value="pantry"><PackageOpen/><span>Pantry</span></TabsTrigger><TabsTrigger value="settings"><Settings/><span>Settings</span></TabsTrigger></TabsList>
    <Dialog open={editorOpen} onOpenChange={open => { if (!open) closeEditor(); }}><DialogContent className="item-dialog"><DialogHeader><DialogTitle>{editing ? "Edit item" : `Add to ${tab === "pantry" ? "Pantry" : "Grocery"}`}</DialogTitle><DialogDescription>Keep it quick. Quantity is optional.</DialogDescription></DialogHeader><div className="form-stack"><label>Description<Input autoFocus maxLength={120} list="item-suggestions" value={description} onChange={e => setDescription(e.target.value)} placeholder="What do you need?" /></label><datalist id="item-suggestions">{suggestions.map(s => <option key={s} value={s}/>)}</datalist><label>Quantity <span>Optional</span><Input maxLength={40} value={quantity} onChange={e => setQuantity(e.target.value)} placeholder="2, 3 cans, 1 lb…" /></label>{formError && <p className="form-error">{formError}</p>}</div><DialogFooter className="dialog-actions">{editing && <Button variant="ghost" className="delete-button" onClick={() => setDeleteOpen(true)}><Trash2/>Delete</Button>}<Button variant="ghost" onClick={closeEditor}>Cancel</Button><Button onClick={saveItem}>Save</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={clearOpen} onOpenChange={setClearOpen}><AlertDialogContent className="confirm-dialog"><AlertDialogHeader><AlertDialogTitle>Clear completed items?</AlertDialogTitle><AlertDialogDescription>This removes all {completed.length} completed {completed.length === 1 ? "item" : "items"} from Grocery. The action will remain in History.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={clearCompleted}>Clear completed</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent className="confirm-dialog"><AlertDialogHeader><AlertDialogTitle>Delete “{editing?.description}”?</AlertDialogTitle><AlertDialogDescription>This removes it from Jamjar. The action will remain in History.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={remove}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </Tabs>;
}
